#!/bin/sh

echo "Pre-commit hook: Lint & format via Spotless for Gradle"
stagedFiles=$(git diff --staged --name-only)
./gradlew spotlessApply
for file in $stagedFiles; do
  if test -f "$file"; then
    git add "$file"
  fi
done